# Generated by Django 5.2.8 on 2025-11-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_workoutvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutvideo',
            name='article',
        ),
    ]
