# Generated by Django 5.2.8 on 2025-11-14 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_workoutvideo_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
