# Generated by Django 5.2.8 on 2025-11-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='media_url',
        ),
    ]
