# Generated by Django 5.2.8 on 2026-10-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscriptionplan_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('initial', 'Initial workouts'), ('daily', 'Daily workout')], default='initial', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Running'), ('retrying', 'Retrying'), ('success', 'Completed'), ('failure', 'Failed'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_generation_jobs', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Workout generation job',
                'verbose_name_plural': 'Workout generation jobs',
                'db_table': 'workout_generation_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
