services:
  redis:
    image: "redis:latest"
    container_name: "gymgeniusai_redis"
    volumes:
      - redis_data:/data
  
  postgres:
    image: "postgres:latest"
    container_name: "gymgeniusai_postgres"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn GymGeniusAI.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    env_file:
      - .env
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
    expose:
      - "8000"
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: "gymgeniusai_nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/staticfiles
      - media_data:/app/media
    depends_on:
      - web
  celery:
    build: .
    command: celery -A GymGeniusAI worker --loglevel=info
    env_file:
      - .env
    volumes:
      - media_data:/app/media
    depends_on:
      - redis
  
volumes:
  redis_data:
    driver: local
  pgdata:
  media_data:
  static_data:

    