services:
  redis:
    image: "redis:latest"
    container_name: "gymgeniusai_redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn GymGeniusAI.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A GymGeniusAI worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
  
volumes:
  redis_data:
    driver: local

    