# -*- coding: utf-8 -*-
"""Kenzeno(Nutrition target).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBWiJtpV3sBT6Emir1NEU4qrxIqu6fKv
"""

import os
from openai import OpenAI
import json, base64
# from google.colab import userdata  # For Colab secrets
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'GymGeniusAI.settings')
from django.conf import settings

o = OpenAI(api_key=settings.OPENAI_API_KEY)

def get_target_calories(
    gender,
    age,
    weight_kg,
    height_cm,
    goal,
    activity_level,
    username,
    current_query=None,
    image_summary=None
):
    """
    Estimate the user's target daily calorie intake based on
    fitness goal, body composition, and activity level.
    Returns a clean JSON with only calorie target and rationale.
    """

    try:
        system_prompt = (
            "You are a certified fitness nutritionist. "
            "Your job is to calculate the user's estimated daily calorie target "
            "based on gender, age, height, weight, activity level, and fitness goal. "
            "If a body image summary is provided, consider it when adjusting the estimate. "
            "Base your reasoning roughly on TDEE (Total Daily Energy Expenditure) principles, "
            "with ±15% adjustment for goals like gaining or losing weight. "
            "Output valid JSON only, in this format:\n\n"
            "{\n"
            "  'username': 'string',\n"
            "  'goal': 'string',\n"
            "  'target_calories_per_day': int,\n"
            "}"
        )

        user_data = f"""
Username: {username}
Gender: {gender}
Age: {age}
Weight: {weight_kg} kg
Height: {height_cm} cm
Activity Level: {activity_level}
Goal: {goal}
Body Image Summary: {image_summary or "N/A"}
User Query: {current_query or "Calculate my daily calorie target."}
"""

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_data}
        ]

        response = o.chat.completions.create(
            model="gpt-4o",
            temperature=0.3,
            response_format={"type": "json_object"},
            messages=messages
        )

        return json.loads(response.choices[0].message.content)

    except Exception as e:
        return {"error": str(e)}

target = get_target_calories(
    gender="male",
    age=25,
    weight_kg=70,
    height_cm=175,
    goal="gain_weight",
    activity_level="intermediate",
    username="Salman",
    current_query="How many calories should I eat daily?",
    image_summary="Lean physique with moderate muscle tone, needs mild surplus."
)

print(json.dumps(target, indent=2))

