# Generated by Django 5.2.7 on 2025-10-23 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('meta', models.JSONField(default=dict, help_text='Additional event metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Log',
                'verbose_name_plural': 'Analytics Logs',
                'db_table': 'analytics_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('feedback', 'Feedback'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('complaint', 'Complaint')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Report',
                'verbose_name_plural': 'Feedback Reports',
                'db_table': 'feedback_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
