# Generated by Django 5.2.8 on 2025-11-07 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_gallery/')),
                ('image_type', models.CharField(choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back')], max_length=20)),
                ('ai_detected', models.BooleanField(default=False, help_text='AI body composition analysis')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of body composition', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Gallery Image',
                'verbose_name_plural': 'User Gallery Images',
                'db_table': 'user_gallery',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
