# Generated by Django 5.2.7 on 2025-10-23 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255)),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('progress', 'Progress'), ('achievement', 'Achievement')], max_length=20)),
                ('ai_detected', models.BooleanField(default=False, help_text='AI body composition analysis')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Gallery Image',
                'verbose_name_plural': 'User Gallery Images',
                'db_table': 'user_gallery',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
