# Generated by Django 5.2.7 on 2025-10-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergallery',
            name='image_type',
            field=models.CharField(choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back')], max_length=20),
        ),
    ]
