# Generated by Django 5.2.8 on 2026-01-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='exercise_videos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_videos', to='accounts.coach')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='workouts.exercise')),
            ],
            options={
                'verbose_name': 'Exercise Video',
                'verbose_name_plural': 'Exercise Videos',
                'db_table': 'exercise_videos',
                'ordering': ['-uploaded_at'],
                'unique_together': {('exercise', 'coach')},
            },
        ),
    ]
