# Generated by Django 5.2.8 on 2026-01-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercisevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisevideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='exercise_videos/'),
        ),
    ]
