# Generated by Django 5.2.8 on 2026-09-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_exercisevideo_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkout',
            name='origin',
            field=models.CharField(choices=[('initial', 'Initial'), ('daily', 'Daily'), ('manual', 'Manual')], default='initial', help_text='Origin of the workout (initial account creation, daily session, or manual)', max_length=20),
        ),
    ]
