# Generated by Django 5.2.8 on 2025-11-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_calorie_target',
            field=models.FloatField(default=0),
        ),
    ]
