# Generated by Django 5.2.7 on 2025-10-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('try_ai_coach', 'Try AI Coach'), ('gain_endurance', 'Gain Endurance')], max_length=50, null=True),
        ),
    ]
