# Generated by Django 5.2.8 on 2026-01-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calorie_target_updated_at',
            field=models.DateField(blank=True, help_text='Last date when calorie target was updated', null=True),
        ),
    ]
