# Generated by Django 5.2.8 on 2025-11-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_daily_calorie_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_workouts_generated',
            field=models.BooleanField(default=False, help_text='Whether initial AI workouts have been generated'),
        ),
    ]
