# Generated by Django 5.2.8 on 2026-06-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_calorie_target_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='product_id',
            field=models.CharField(blank=True, help_text='RevenueCat/Store Product ID', max_length=100, null=True, unique=True),
        ),
    ]
