# Generated by Django 5.2.7 on 2025-10-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_coach_alter_user_coach_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_workout_time',
            field=models.TimeField(blank=True, help_text='Preferred time of day for workouts', null=True),
        ),
    ]
