# Generated by Django 5.2.7 on 2025-10-24 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Meal Category',
                'verbose_name_plural': 'Meal Categories',
                'db_table': 'meal_categories',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('preparation', models.TextField(blank=True, null=True)),
                ('cook_time_min', models.IntegerField(blank=True, help_text='Cooking time in minutes', null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('macros', models.JSONField(default=dict, help_text='Macronutrients (protein, carbs, fats)')),
                ('micros', models.JSONField(default=dict, help_text='Micronutrients (vitamins, minerals)')),
                ('ai_rating', models.FloatField(blank=True, help_text='AI health rating', null=True)),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.mealcategory')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'db_table': 'meals',
            },
        ),
        migrations.CreateModel(
            name='UserMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=50)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Meal Plan',
                'verbose_name_plural': 'User Meal Plans',
                'db_table': 'user_meal_plans',
                'ordering': ['date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='UserUploadedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255)),
                ('ai_analysis', models.JSONField(default=dict, help_text='AI nutrition analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Uploaded Meal',
                'verbose_name_plural': 'User Uploaded Meals',
                'db_table': 'user_uploaded_meals',
                'ordering': ['-created_at'],
            },
        ),
    ]
