# Generated by Django 5.2.8 on 2025-11-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedmeal',
            name='imporovements',
            field=models.TextField(blank=True, help_text='AI suggested improvements', null=True),
        ),
        migrations.AddField(
            model_name='useruploadedmeal',
            name='macronutrients',
            field=models.JSONField(default=dict, help_text='Macronutrients (protein, carbs, fats)'),
        ),
        migrations.AddField(
            model_name='useruploadedmeal',
            name='micronutrients',
            field=models.JSONField(default=dict, help_text='Micronutrients (vitamins, minerals)'),
        ),
        migrations.AlterField(
            model_name='useruploadedmeal',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='user_meals/'),
        ),
    ]
