# Generated by Django 5.2.8 on 2025-11-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_useruploadedmeal_imporovements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useruploadedmeal',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='useruploadedmeal',
            old_name='imporovements',
            new_name='improvements',
        ),
    ]
