# Generated by Django 5.2.8 on 2025-11-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_rename_image_url_useruploadedmeal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadedmeal',
            name='estimated_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useruploadedmeal',
            name='meal_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
