# Generated by Django 5.2.8 on 2025-11-07 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exercise Category',
                'verbose_name_plural': 'Exercise Categories',
                'db_table': 'exercise_categories',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Exercise_Now()_8069', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('muscle_group', models.CharField(blank=True, help_text='e.g., Chest, Back, Legs, Arms, Core, Full Body', max_length=100, null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('default_sets', models.IntegerField(default=3, help_text='Default number of sets')),
                ('default_reps', models.IntegerField(default=10, help_text='Default number of repetitions')),
                ('default_duration_seconds', models.IntegerField(blank=True, help_text='Default duration in seconds (for timed exercises)', null=True)),
                ('default_rest_time', models.IntegerField(default=60, help_text='Default rest time in seconds')),
                ('calories_per_rep', models.FloatField(default=0.5, help_text='Estimated calories burned per rep')),
                ('equipment_needed', models.CharField(blank=True, help_text='e.g., Dumbbells, Barbell, None', max_length=255, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workouts.exercisecategory')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'db_table': 'exercises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Workout_Now()_5194', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by_ai', models.BooleanField(default=False, help_text='Whether this was created by AI')),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True)),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('estimated_calories', models.IntegerField(blank=True, help_text='Estimated calories to burn', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this workout is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Workout',
                'verbose_name_plural': 'User Workouts',
                'db_table': 'user_workouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_exercises', models.JSONField(default=list, help_text='List of completed user_exercise IDs')),
                ('completion_percentage', models.FloatField(default=0.0, help_text='Percentage of exercises completed')),
                ('actual_duration', models.IntegerField(blank=True, help_text='Actual duration in minutes', null=True)),
                ('actual_calories', models.FloatField(blank=True, help_text='Actual calories burned', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, help_text='User rating (1-5)', null=True)),
                ('difficulty_rating', models.CharField(blank=True, choices=[('too_easy', 'Too Easy'), ('just_right', 'Just Right'), ('too_hard', 'Too Hard')], max_length=20, null=True)),
                ('user_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='workouts.userworkout')),
            ],
            options={
                'verbose_name': 'Workout Progress',
                'verbose_name_plural': 'Workout Progress Records',
                'db_table': 'workout_progress',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=3, help_text='Number of sets')),
                ('reps', models.IntegerField(default=10, help_text='Number of repetitions per set')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration in seconds (for timed exercises)', null=True)),
                ('rest_time', models.IntegerField(default=60, help_text='Rest time in seconds between sets')),
                ('order', models.IntegerField(default=0, help_text='Order of exercise in workout')),
                ('notes', models.TextField(blank=True, help_text='AI-generated or custom notes for this exercise', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exercises', to='workouts.exercise')),
                ('user_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exercises', to='workouts.userworkout')),
            ],
            options={
                'verbose_name': 'User Exercise',
                'verbose_name_plural': 'User Exercises',
                'db_table': 'user_exercises',
                'ordering': ['order'],
                'unique_together': {('user_workout', 'exercise', 'order')},
            },
        ),
    ]
