# Generated by Django 5.2.7 on 2025-10-24 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('calories_burn', models.IntegerField(help_text='Estimated calories burned')),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'db_table': 'workouts',
            },
        ),
        migrations.CreateModel(
            name='WorkoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Workout Category',
                'verbose_name_plural': 'Workout Categories',
                'db_table': 'workout_categories',
            },
        ),
        migrations.CreateModel(
            name='UserWorkoutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_rounds', models.JSONField(default=list, help_text='List of completed round IDs')),
                ('date', models.DateField()),
                ('calories_burned', models.FloatField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_progress', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
            options={
                'verbose_name': 'User Workout Progress',
                'verbose_name_plural': 'User Workout Progress',
                'db_table': 'user_workout_progress',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workouts.workoutcategory'),
        ),
        migrations.CreateModel(
            name='WorkoutRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('round_order', models.IntegerField(help_text='Order of the round')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Workout Round',
                'verbose_name_plural': 'Workout Rounds',
                'db_table': 'workout_rounds',
                'ordering': ['round_order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('reps', models.IntegerField(blank=True, help_text='Number of repetitions', null=True)),
                ('sets', models.IntegerField(blank=True, help_text='Number of sets', null=True)),
                ('rest_seconds', models.IntegerField(blank=True, help_text='Rest time in seconds', null=True)),
                ('video_url', models.URLField(blank=True, max_length=255, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutround')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'db_table': 'exercises',
            },
        ),
    ]
