# Generated by Django 5.2.8 on 2025-11-07 20:13

import workouts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(default=workouts.models.generate_exercise_name, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userworkout',
            name='name',
            field=models.CharField(default=workouts.models.generate_workout_name, max_length=255),
        ),
    ]
