# Generated by Django 5.2.7 on 2025-11-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_refactor_workout_models'),
    ]

    operations = [
    ]
