# Generated by Django 5.2.8 on 2025-11-13 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Custom Routine', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_routine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Routine',
                'verbose_name_plural': 'Custom Routines',
                'db_table': 'custom_routines',
            },
        ),
        migrations.CreateModel(
            name='CustomRoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(blank=True, help_text='Number of sets', null=True)),
                ('reps', models.IntegerField(blank=True, help_text='Number of repetitions per set', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Duration in seconds (for timed exercises)', null=True)),
                ('rest_time', models.IntegerField(blank=True, help_text='Rest time in seconds between sets', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order of exercise in routine')),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('custom_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.customroutine')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_routines', to='workouts.exercise')),
            ],
            options={
                'verbose_name': 'Custom Routine Exercise',
                'verbose_name_plural': 'Custom Routine Exercises',
                'db_table': 'custom_routine_exercises',
                'ordering': ['order', 'added_at'],
                'unique_together': {('custom_routine', 'exercise')},
            },
        ),
    ]
