# Generated by Django 5.2.8 on 2025-11-13 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_customroutine_customroutineexercise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRoutineExerciseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_sets', models.IntegerField(help_text='Actual sets completed')),
                ('actual_reps', models.IntegerField(blank=True, help_text='Actual reps completed per set', null=True)),
                ('actual_duration_seconds', models.IntegerField(blank=True, help_text='Actual duration in seconds', null=True)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('calories_burned', models.FloatField(help_text='Estimated calories burned')),
                ('notes', models.TextField(blank=True, null=True)),
                ('difficulty_rating', models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], max_length=20, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('custom_routine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='workouts.customroutineexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercise_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Routine Exercise Completion',
                'verbose_name_plural': 'Custom Routine Exercise Completions',
                'db_table': 'custom_routine_exercise_completions',
                'ordering': ['-completed_at'],
            },
        ),
    ]
