# Generated by Django 5.2.8 on 2025-11-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_customroutineexercisecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_images/'),
        ),
    ]
