# Generated by Django 5.2.8 on 2025-11-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_exercise_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='video_url',
        ),
    ]
