# -*- coding: utf-8 -*-
"""Kenzeno(Workout Suggestion).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b9CvtJ9ED4ZFKNmtFZLX0Ezq43JJC7B1
"""
import os
import pandas as pd
from tqdm import tqdm
import openai
from pinecone import Pinecone, ServerlessSpec
from langchain_openai import OpenAIEmbeddings
from langchain_pinecone import PineconeVectorStore
from langchain_text_splitters import RecursiveCharacterTextSplitter
import json

import langchain
langchain.__version__

import os, django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "GymGeniusAI.settings")
django.setup()
from GymGeniusAI.settings import OPENAI_API_KEY, PINECONE_API_KEY


# ==================== CONFIG ====================
INDEX_NAME = "workout-index"
EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIM = 1536

# Set your OpenAI API key
# Replace "YOUR_OPENAI_API_KEY" with your actual key or ensure it's set as an environment variable
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
# Set your Pinecone API key
# Replace "YOUR_PINECONE_API_KEY" with your actual key or ensure it's set as an environment variable
os.environ["PINECONE_API_KEY"] = PINECONE_API_KEY  # <<< Make sure to replace this with your actual Pinecone API Key!

# Initialize OpenAI client
o = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Initialize Pinecone
pc = Pinecone(api_key=os.getenv("PINECONE_API_KEY"))

if INDEX_NAME not in [i.name for i in pc.list_indexes()]:
    print(f" Creating index: {INDEX_NAME}")
    pc.create_index(
        name=INDEX_NAME,
        dimension=EMBEDDING_DIM,
        metric="cosine",
        spec=ServerlessSpec(cloud="aws", region="us-east-1")
    )
else:
    print(f"Index already exists: {INDEX_NAME}")

# Load your workout dataset
df = pd.read_csv("gym_workouts_full.csv")   # replace with your path
df = df.fillna("").astype(str)

print(f"Dataset loaded with {len(df)} rows")

# Combine columns into one text field for embedding (optional)
def combine_row(row):
    return " | ".join([f"{col}: {row[col]}" for col in df.columns if row[col]])

df["combined_text"] = df.apply(combine_row, axis=1)

splitter = RecursiveCharacterTextSplitter(
    chunk_size=2000,
    chunk_overlap=100,
    separators=["\n", ".", "!", "?", ";", ",", " "]
)

# Each row = 1 chunk
texts = []
metadata = []

for idx, row in df.iterrows():
    chunks = splitter.split_text(row["combined_text"])
    for chunk in chunks:
        texts.append(chunk)
        metadata.append({"row_index": idx})

embeddings = OpenAIEmbeddings(model=EMBEDDING_MODEL)

# Connect to existing or create vectorstore
vectorstore = PineconeVectorStore.from_existing_index(
    index_name=INDEX_NAME,
    embedding=embeddings
)

# Upload embeddings if not already stored
print("Uploading embeddings to Pinecone...")
ids = [f"workout-{i}" for i in range(len(texts))]
vectorstore.add_texts(texts=texts, metadatas=metadata, ids=ids)
print(f"Uploaded {len(texts)} chunks to Pinecone.")

def retrieve_workout_info(query, top_k=20):
    embeddings = OpenAIEmbeddings(model=EMBEDDING_MODEL)
    vectorstore = PineconeVectorStore.from_existing_index(
        index_name=INDEX_NAME,
        embedding=embeddings
    )

    results = vectorstore.similarity_search(query, k=top_k)
    print("Top Results:")
    for i, res in enumerate(results, 1):
        print(f"\nResult {i}:")
        print(res.page_content[:500])
        print("Metadata:", res.metadata)
    return results

def generate_dataset_based_workout(
    gender,
    age,
    weight_kg,
    height_cm,
    goal,
    activity_level,
    username,
    image_summary=None,
    workout_logs=None,      # <= NEW
    top_k=7
):
    """
    Generate a personalized workout plan based on:
    - User profile
    - Retrieved dataset workouts from Pinecone
    - User's last 7 days workout logs (if provided)

    The LLM is restricted to ONLY use dataset exercises.
    """

    try:
        embeddings = OpenAIEmbeddings(model=EMBEDDING_MODEL)
        vectorstore = PineconeVectorStore.from_existing_index(
            index_name=INDEX_NAME,
            embedding=embeddings
        )

        query = f"Workout plan for {goal}, activity level: {activity_level}, gender: {gender}"
        retrieved_docs = vectorstore.similarity_search(query, k=top_k)
        context = "\n\n".join([doc.page_content for doc in retrieved_docs])

        workout_history_text = (
            json.dumps(workout_logs, indent=2)
            if workout_logs
            else "No previous logs available."
        )

        system_prompt = (
            "You are a certified strength and conditioning coach. "
            "Use ONLY the exercises provided inside 'Dataset Context'. "
            "Do NOT invent new exercises. "
            "Personalize the workout using user profile + previous 7 days of workout logs. "
            "You must apply progressive overload where appropriate and avoid repeating identical exercises from previous days. "
            "Minimum 5 exercises. No duplicates. "
            "Always output valid JSON only.\n\n"
            "Output Format:\n"
            "[\n"
            "  {\n"
            "    'workout_name': 'string',\n"
            "    'description': 'string',\n"
            "    'difficulty': 'Beginner' | 'Intermediate' | 'Advanced',\n"
            "    'estimated_duration': int,\n"
            "    'estimated_calories': int,\n"
            "    'exercises': [\n"
            "      {\n"
            "        'name': 'string',\n"
            "        'sets': int,\n"
            "        'reps': int,\n"
            "        'duration_seconds': int,\n"
            "        'rest_time': int,\n"
            "        'notes': 'string'\n"
            "      }\n"
            "    ]\n"
            "  }\n"
            "]"
        )

        user_profile = f"""
Username: {username}
Gender: {gender}
Age: {age}
Weight: {weight_kg} kg
Height: {height_cm} cm
Goal: {goal}
Activity Level: {activity_level}
Body Image Summary: {image_summary or "N/A"}

Previous 7 Days Workout Logs:
{workout_history_text}

Dataset Context (workouts retrieved from your indexed dataset):
{context}
"""

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_profile}
        ]

        response = o.chat.completions.create(
            model="gpt-4o",
            temperature=0.1,
            response_format={"type": "json_object"},
            messages=messages
        )

        return json.loads(response.choices[0].message.content)

    except Exception as e:
        return {"error": str(e)}

workout_plan = generate_dataset_based_workout(
    gender="female",
    age=29,
    weight_kg=62,
    height_cm=165,
    goal="gain_weight",
    activity_level="intermediate",
    username="Sara",
    image_summary="Your posture is looking pretty solid with that straight spine alignment. The abdominal area could use some core strengthening, and overall, your muscle tone is average, so focusing on full-body workouts will help balance and tone everything up nicely!"
)

print(json.dumps(workout_plan, indent=2))

workout_plan = generate_dataset_based_workout(
    gender="male",
    age=29,
    weight_kg=62,
    height_cm=165,
    goal="gain_weight",
    activity_level="intermediate",
    username="Sara",
    image_summary="Your posture is looking pretty solid with that straight spine alignment. The abdominal area could use some core strengthening, and overall, your muscle tone is average, so focusing on full-body workouts will help balance and tone everything up nicely!"
)

print(json.dumps(workout_plan, indent=2))

