# -*- coding: utf-8 -*-
"""Kenzeno(Chatbot).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10qDPw_R8dUASldk8wK24Tl3ftYpgp-Ae
"""

import json
from openai import OpenAI
# from google.colab import userdata
import re
import base64
import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'GymGeniusAI.settings')
from django.conf import settings


o = OpenAI(api_key=settings.OPENAI_API_KEY)

def analyze_user_image(base64_image):
    """
    Analyzes a user's full-body image and returns a short,
    fitness-relevant description (posture, symmetry, muscle tone, etc.).
    """
    try:
        response = o.chat.completions.create(
            model="gpt-4o-mini",
            temperature=0.2,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a professional fitness assessment assistant. "
                        "Describe the person's physique only in factual, training-relevant terms. "
                        "Mention posture, symmetry, muscle tone, and any visible balance issues. "
                        "Avoid comments on attractiveness, race, or emotion. "
                        "Keep your output concise (1–3 lines)."
                    )
                },
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": "Analyze this full-body image for training-relevant observations only."
                        },
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}
                        }
                    ]
                }
            ]
        )

        return response.choices[0].message.content.strip()

    except Exception as e:
        print("Error in analyze_user_image:", e)
        return "Image analysis unavailable."


def fitness_coach_ai(
    gender,
    age,
    weight_kg,
    height_cm,
    goal,
    activity_level,
    username,
    coach_name,
    current_query,
    image_summary=None,
    conversation_history=None
):
    """
    Main AI chat handler for FitCoach.
    Always returns a clean JSON object with plain-text keys:
      - reply
      - image_summary
    """
    try:
        chatbot_name = "FitCoach"

        system_message = {
            "role": "system",
            "content": f"""
You are "{chatbot_name}", an AI fitness coach that adopts one of four personas.

## Personas
- John — tough love, no excuses, best-results mindset.
- Selma — warm, supportive, emotionally smart.
- Jara — sassy, humorous, and hyper-motivating.
- Chris — professional, focused, efficient.

Active persona: {coach_name}

## User Profile
gender: {gender}
age: {age}
weight_kg: {weight_kg}
height_cm: {height_cm}
goal: {goal}
activity_level: {activity_level}
username: {username}

## Image Analysis Summary
{image_summary or "No image provided."}

## Behavior Guidelines
- Always speak as {coach_name}.
- Be conversational, motivational, and clear.
- Provide structured workout or nutrition guidance.
- Use image_summary for posture/mobility cues.
- Use metric units (kg, cm, km).
- NEVER comment on attractiveness, race, or emotion.
- Respond ONLY in JSON format.

## JSON Response Format
{{
  "reply": "Main assistant message to the user",
  "image_summary": "Shortly analyze each portion of muscle from the image"
}}

Conversation history for context:
{conversation_history}
"""
        }

        user_message = {"role": "user", "content": current_query}

        response = o.chat.completions.create(
            model="gpt-4o",
            temperature=0.6,
            messages=[system_message, user_message],
        )

        raw_output = response.choices[0].message.content.strip()

        # Try to parse JSON safely
        try:
            parsed = json.loads(raw_output)
        except json.JSONDecodeError:
            parsed = {
                "reply": raw_output,
                "image_summary": image_summary or "N/A"
            }

        parsed.setdefault("reply", "I'm ready to help you get fitter!")
        parsed.setdefault("image_summary", image_summary or "N/A")


        def clean_text(text):
            if not isinstance(text, str):
                return text

            text = re.sub(r"\*\*|##|###|\*", "", text)  # remove markdown
            text = re.sub(r"\\u[0-9a-fA-F]{4}", "", text)  # remove unicode escapes
            text = re.sub(r"[\U0001F600-\U0001F64F]", "", text)  # remove emojis
            text = re.sub(r"[\U0001F300-\U0001F5FF]", "", text)
            text = re.sub(r"[\U0001F680-\U0001F6FF]", "", text)
            text = re.sub(r"[\U0001F1E0-\U0001F1FF]", "", text)
            text = re.sub(r"\s*\n\s*", " ", text)  # collapse newlines
            text = re.sub(r"\s{2,}", " ", text)  # remove multiple spaces
            return text.strip()

        parsed["reply"] = clean_text(parsed["reply"])
        parsed["image_summary"] = clean_text(parsed["image_summary"])

        return parsed

    except Exception as e:
        print("Error in fitness_coach_ai:", e)
        return {
            "reply": f"Error: {str(e)}",
            "image_summary": image_summary or "N/A"
        }

# from google.colab import files
# import base64, json

# # Step 1: Upload your full-body photo
# print("Please upload your full-body image...")
# uploaded = files.upload()

# # Grab the uploaded filename
# filename = list(uploaded.keys())[0]

# # Step 2: Convert to base64
with open('image copy.png', "rb") as f:
    base64_img = base64.b64encode(f.read()).decode("utf-8")

# # Use analyze_user_image (not fitness_coach_ai)
img_summary = analyze_user_image(base64_img)
print("Image Summary:", img_summary)
# Step 3: Pass image summary to the fitness coach
response = fitness_coach_ai(
    gender="male",
    age=25,
    weight_kg=70,
    height_cm=175,
    goal="lose_weight",
    activity_level="beginner",
    username="Salman",
    coach_name="Jara",
    current_query="Hey coach, how can I improve my physique? I'm focusing on specific muscles to tone and strengthen.",
    image_summary=img_summary,
    conversation_history=None
)

# Step 4: Display clean JSON response
print(json.dumps(response, indent=2, ensure_ascii=False))

