# -*- coding: utf-8 -*-
"""Kenzeno(meal analyze).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-GtjpUpLnXgC2YvFtpO-hJRNuTzjwND
"""

from openai import OpenAI
import json, base64
# from google.colab import userdata  # For Colab secrets
import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'GymGeniusAI.settings')
from django.conf import settings

o = OpenAI(api_key=settings.OPENAI_API_KEY)

def analyze_single_meal(base64_image, meal_name="Meal"):
    """
    Analyze a single meal image for its nutritional profile and improvement tips.
    """

    try:
        system_prompt = (
            "You are a certified AI nutritionist. "
            "Analyze the visible foods in the image and provide:\n"
            "- Estimated calories, protein, carbs, and fat.\n"
            "- Key micronutrients (vitamin C, calcium, iron, etc.).\n"
            "- A short health insight (2-3 sentences) summarizing overall meal quality.\n"
            "- A 2-line improvement suggestion (how to make it healthier or better balanced).\n"
            "**NOTE** DO NOT GIVE DIFFERENT DIFFERENT INFORMATION FOR SAME MEAL"
            "Return only valid JSON with this structure:\n\n"
            "{\n"
            "  'meal_name': 'string',\n"
            "  'estimated_calories': int,\n"
            "  'macronutrients': {'protein_g': ..., 'carbs_g': ..., 'fat_g': ...},\n"
            "  'micronutrients': {'vitamin_c_mg': ..., 'iron_mg': ..., 'calcium_mg': ...},\n"
            "  'overall_health_insight': 'string',\n"
            "  'improvement_suggestion': 'string'\n"
            "}"
        )

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": [
                {"type": "text", "text": f"Analyze this {meal_name.lower()} image."},
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}}
            ]}
        ]

        response = o.chat.completions.create(
            model="gpt-4o",
            temperature=0.4,
            response_format={"type": "json_object"},
            messages=messages
        )

        return json.loads(response.choices[0].message.content)

    except Exception as e:
        return {"error": str(e)}

with open("image.png", "rb") as f:
    meal_base64 = base64.b64encode(f.read()).decode("utf-8")

meal_analysis = analyze_single_meal(meal_base64, meal_name="Lunch")
print(json.dumps(meal_analysis, indent=2))

