# Generated by Django 5.2.8 on 2025-11-11 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle the model move
        # State-only operation: tells Django the model exists in utils app
        # Database operation: empty (table already exists from notifications app)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=150)),
                        ('message', models.TextField()),
                        ('notification_type', models.CharField(choices=[('reminder', 'Reminders'), ('system', 'System Alerts')], max_length=50)),
                        ('is_read', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Notification',
                        'verbose_name_plural': 'Notifications',
                        'db_table': 'notifications',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[
                # No database operations needed - table already exists
            ],
        ),
    ]
