# Generated by Django 5.2.8 on 2025-11-20 22:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique code for programmatic use', max_length=50, unique=True)),
                ('points', models.IntegerField(help_text='Points awarded for this activity')),
                ('description', models.TextField(blank=True, null=True)),
                ('max_per_day', models.IntegerField(blank=True, help_text='Maximum times this activity can be counted per day (None for unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity Type',
                'verbose_name_plural': 'Activity Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master')], max_length=20, unique=True)),
                ('level', models.IntegerField(help_text='Order of rank (1=lowest)', unique=True)),
                ('promotion_threshold', models.FloatField(help_text='Top X% get promoted weekly (e.g., 20.0 means top 20%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('demotion_threshold', models.FloatField(default=0.0, help_text='Bottom X% get demoted weekly (e.g., 10.0 means bottom 10%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('min_points_required', models.IntegerField(default=0, help_text='Minimum points to maintain this rank')),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color_code', models.CharField(default='#808080', help_text='Hex color code', max_length=7)),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_check_in', models.DateField(blank=True, null=True)),
                ('total_check_ins', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Streak',
                'verbose_name_plural': 'User Streaks',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data about the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('week_start', models.DateField(help_text='Start of the week this transaction belongs to')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.activitytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_b86e52_idx'), models.Index(fields=['week_start', 'user'], name='gamificatio_week_st_967b77_idx'), models.Index(fields=['activity_type', 'created_at'], name='gamificatio_activit_a7c8c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Reason for rank change', max_length=100)),
                ('weekly_points', models.IntegerField()),
                ('position_in_old_rank', models.IntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('week_start', models.DateField()),
                ('new_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_rank_history', to='gamification.rank')),
                ('old_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_rank_history', to='gamification.rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rank History',
                'verbose_name_plural': 'Rank Histories',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['user', '-changed_at'], name='gamificatio_user_id_001e4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('weekly_points', models.IntegerField(default=0)),
                ('rank_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='gamification.rank')),
                ('highest_rank_achieved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_rank_users', to='gamification.rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_rank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Rank',
                'verbose_name_plural': 'User Ranks',
                'ordering': ['-weekly_points', '-total_points'],
                'indexes': [models.Index(fields=['-weekly_points', '-total_points'], name='gamificatio_weekly__353584_idx'), models.Index(fields=['current_rank', '-weekly_points'], name='gamificatio_current_439eb4_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('position', models.IntegerField(help_text='Position within their rank/league')),
                ('position_in_rank', models.IntegerField(help_text='Position among all users in same rank')),
                ('total_users_in_rank', models.IntegerField(help_text='Total users in this rank this week')),
                ('weekly_points', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('rank_changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_weekly_leaderboards', to='gamification.rank')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_leaderboards', to='gamification.rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Leaderboard',
                'verbose_name_plural': 'Weekly Leaderboards',
                'ordering': ['week_start', 'rank__level', 'position_in_rank'],
                'indexes': [models.Index(fields=['week_start', 'rank', 'position_in_rank'], name='gamificatio_week_st_516145_idx'), models.Index(fields=['user', '-week_start'], name='gamificatio_user_id_f917fa_idx')],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
