# Generated by Django 5.2.8 on 2026-01-06 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique code for programmatic use', max_length=50, unique=True)),
                ('points', models.IntegerField(help_text='Points awarded for this activity')),
                ('description', models.TextField(blank=True, null=True)),
                ('max_per_day', models.IntegerField(blank=True, help_text='Maximum times this activity can be counted per day (None for unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity Type',
                'verbose_name_plural': 'Activity Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master')], max_length=20, unique=True)),
                ('level', models.IntegerField(help_text='Order of rank (1=lowest)', unique=True)),
                ('promotion_threshold', models.FloatField(help_text='Top X% get promoted weekly (e.g., 20.0 means top 20%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('demotion_threshold', models.FloatField(default=0.0, help_text='Bottom X% get demoted weekly (e.g., 10.0 means bottom 10%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('min_points_required', models.IntegerField(default=0, help_text='Minimum points to maintain this rank')),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color_code', models.CharField(default='#808080', help_text='Hex color code', max_length=7)),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('DAILY', 'Daily Challenge'), ('WEEKLY', 'Weekly Challenge')], max_length=10)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('completion_points', models.IntegerField(help_text='Points awarded for completing the challenge')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('exercises', models.JSONField(default=list, help_text='List of exercises with detailed information. Each exercise should include:\n- exercise_id (int, optional): ID from Exercise model to auto-populate details\n- name (str): Exercise name\n- sets (int): Number of sets\n- reps (int, optional): Reps per set\n- duration_seconds (int, optional): Duration for timed exercises\n- rest_time (int): Rest time between sets in seconds\n- notes (str, optional): Additional instructions\nIf exercise_id is provided, description, video, muscle_group, difficulty, equipment_needed, calories_per_rep, and tips will be auto-populated from Exercise model.')),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('estimated_calories', models.IntegerField(blank=True, help_text='Estimated calories to burn', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin or system that created this challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gamification_challenges_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data about the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('week_start', models.DateField(help_text='Start of the week this transaction belongs to')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.activitytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Reason for rank change', max_length=100)),
                ('weekly_points', models.IntegerField()),
                ('position_in_old_rank', models.IntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('week_start', models.DateField()),
                ('new_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_rank_history', to='gamification.rank')),
                ('old_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_rank_history', to='gamification.rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rank History',
                'verbose_name_plural': 'Rank Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20)),
                ('completed_exercises', models.JSONField(default=list, help_text='List of completed exercise indices from the challenge')),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('actual_duration', models.IntegerField(blank=True, help_text='Actual duration in minutes', null=True)),
                ('actual_calories', models.FloatField(blank=True, help_text='Actual calories burned', null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('points_claimed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, help_text='User rating (1-5)', null=True)),
                ('difficulty_rating', models.CharField(blank=True, choices=[('too_easy', 'Too Easy'), ('just_right', 'Just Right'), ('too_hard', 'Too Hard')], max_length=20, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='gamification.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Challenge Progress',
                'verbose_name_plural': 'User Challenge Progress Records',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('weekly_points', models.IntegerField(default=0)),
                ('rank_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='gamification.rank')),
                ('highest_rank_achieved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highest_rank_users', to='gamification.rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_rank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Rank',
                'verbose_name_plural': 'User Ranks',
                'ordering': ['-weekly_points', '-total_points'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_check_in', models.DateField(blank=True, null=True)),
                ('total_check_ins', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Streak',
                'verbose_name_plural': 'User Streaks',
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('position', models.IntegerField(help_text='Position within their rank/league')),
                ('position_in_rank', models.IntegerField(help_text='Position among all users in same rank')),
                ('total_users_in_rank', models.IntegerField(help_text='Total users in this rank this week')),
                ('weekly_points', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('rank_changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_weekly_leaderboards', to='gamification.rank')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_leaderboards', to='gamification.rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Leaderboard',
                'verbose_name_plural': 'Weekly Leaderboards',
                'ordering': ['week_start', 'rank__level', 'position_in_rank'],
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['challenge_type', 'is_active', 'start_date'], name='gamificatio_challen_7805af_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['start_date', 'end_date'], name='gamificatio_start_d_ff8bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_b86e52_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['week_start', 'user'], name='gamificatio_week_st_967b77_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['activity_type', 'created_at'], name='gamificatio_activit_a7c8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='rankhistory',
            index=models.Index(fields=['user', '-changed_at'], name='gamificatio_user_id_001e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengeprogress',
            index=models.Index(fields=['user', 'status'], name='gamificatio_user_id_eb6dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengeprogress',
            index=models.Index(fields=['challenge', 'status'], name='gamificatio_challen_758a21_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengeprogress',
            index=models.Index(fields=['-completed_at'], name='gamificatio_complet_39afe9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchallengeprogress',
            unique_together={('user', 'challenge')},
        ),
        migrations.AddIndex(
            model_name='userrank',
            index=models.Index(fields=['-weekly_points', '-total_points'], name='gamificatio_weekly__353584_idx'),
        ),
        migrations.AddIndex(
            model_name='userrank',
            index=models.Index(fields=['current_rank', '-weekly_points'], name='gamificatio_current_439eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyleaderboard',
            index=models.Index(fields=['week_start', 'rank', 'position_in_rank'], name='gamificatio_week_st_516145_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyleaderboard',
            index=models.Index(fields=['user', '-week_start'], name='gamificatio_user_id_f917fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyleaderboard',
            unique_together={('user', 'week_start')},
        ),
    ]
