# Generated by Django 5.2.8 on 2025-11-27 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('DAILY', 'Daily Challenge'), ('WEEKLY', 'Weekly Challenge')], max_length=10)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('completion_points', models.IntegerField(help_text='Points awarded for completing the challenge')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('exercises', models.JSONField(default=list, help_text='List of exercises with sets, reps, etc. Similar to UserExercise structure')),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('estimated_calories', models.IntegerField(blank=True, help_text='Estimated calories to burn', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin or system that created this challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gamification_challenges_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20)),
                ('completed_exercises', models.JSONField(default=list, help_text='List of completed exercise indices from the challenge')),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('actual_duration', models.IntegerField(blank=True, help_text='Actual duration in minutes', null=True)),
                ('actual_calories', models.FloatField(blank=True, help_text='Actual calories burned', null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('points_claimed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, help_text='User rating (1-5)', null=True)),
                ('difficulty_rating', models.CharField(blank=True, choices=[('too_easy', 'Too Easy'), ('just_right', 'Just Right'), ('too_hard', 'Too Hard')], max_length=20, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='gamification.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Challenge Progress',
                'verbose_name_plural': 'User Challenge Progress Records',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['challenge_type', 'is_active', 'start_date'], name='gamificatio_challen_7805af_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['start_date', 'end_date'], name='gamificatio_start_d_ff8bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengeprogress',
            index=models.Index(fields=['user', 'status'], name='gamificatio_user_id_eb6dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengeprogress',
            index=models.Index(fields=['challenge', 'status'], name='gamificatio_challen_758a21_idx'),
        ),
        migrations.AddIndex(
            model_name='userchallengeprogress',
            index=models.Index(fields=['-completed_at'], name='gamificatio_complet_39afe9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userchallengeprogress',
            unique_together={('user', 'challenge')},
        ),
    ]
