# Generated by Django 5.2.8 on 2025-11-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_challenge_userchallengeprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='exercises',
            field=models.JSONField(default=list, help_text='List of exercises with detailed information. Each exercise should include:\n- exercise_id (int, optional): ID from Exercise model to auto-populate details\n- name (str): Exercise name\n- sets (int): Number of sets\n- reps (int, optional): Reps per set\n- duration_seconds (int, optional): Duration for timed exercises\n- rest_time (int): Rest time between sets in seconds\n- notes (str, optional): Additional instructions\nIf exercise_id is provided, description, video, muscle_group, difficulty, equipment_needed, calories_per_rep, and tips will be auto-populated from Exercise model.'),
        ),
    ]
