# Generated by Django 5.2.7 on 2025-10-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Reminders'), ('system', 'System Alerts')], default='reminder', max_length=50),
            preserve_default=False,
        ),
    ]
